name: neuroharmonize-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.4.*
  - matplotlib=3.8.*
  - statsmodels>=0.13
  - patsy
  - nibabel
  - pip
  - pip:
      - neuroHarmonize
      - neuroCombat
